language: php

env:
  global:
  - DB=mysql

services:
  - mysql

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: 7.4
  - php: nightly
  fast_finish: true
  allow_failures:
  - php: nightly

before_script:
  - mysql --version
  - git clone git://github.com/ozh/YOURLS-fr_FR.git user/languages/fr
  - cp user/languages/fr/fr_FR.* user/languages
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp tests/data/config/yourls-tests-config-travis.php user/config.php

install: composer install -d ./tests

script: tests/vendor/bin/phpunit --configuration ./phpunit-travis.xml.dist

notifications:
  email: false
